/** Generate a long-form narrative (markdown) from a structured record. */
export function buildNarrative(rec, index) {
  const label = (id) => index.factorById[id]?.label || id
  const lines = []
  lines.push(`# ${rec.title}`)
  lines.push('')
  lines.push(`*${rec.date} · ${rec.aircraft.type} (${rec.aircraft.registration || 'registration unknown'}) · ${rec.operator} · ${rec.location?.name || ''}*`)
  lines.push('')
  lines.push(`Investigated by **${rec.agencies.find((a) => a.role === 'lead')?.name || rec.agency}**${rec.agencies.filter((a) => a.role !== 'lead').length ? ' with ' + rec.agencies.filter((a) => a.role !== 'lead').map((a) => `${a.code} (${a.role.replace(/_/g, ' ')})`).join(', ') : ''}. ${rec.fatalities === 0 ? 'There were no fatalities.' : `${rec.fatalities ?? 'An unknown number'} of the ${rec.occupants ?? '?'} people on board died.`}`)
  lines.push('')
  lines.push(rec.summary)
  lines.push('')
  lines.push('## The sequence')
  lines.push('')
  const byPhase = []
  for (const e of rec.events) {
    const last = byPhase[byPhase.length - 1]
    if (!last || last.phase !== e.phase) byPhase.push({ phase: e.phase, events: [e] })
    else last.events.push(e)
  }
  for (const group of byPhase) {
    lines.push(`**${(group.phase || 'sequence').replace(/_/g, ' ')}.** ` + group.events.map((e) => `${e.clock ? `At ${e.clock}` : `At ${relText(e.t)}`}${e.actor && e.actor !== 'SYS' && e.actor !== 'ENV' ? ` the ${index.graph.taxonomy.actors[e.actor] || e.actor}` : ''}: ${e.text}${stateText(e.state)}`).join(' '))
    lines.push('')
  }
  if (rec.cvr && rec.cvr.length) {
    lines.push('## From the cockpit voice recorder')
    lines.push('')
    for (const c of rec.cvr) lines.push(`- \`${c.clock || c.t}\` **${c.speaker}**: ${c.text}${c.translation ? ` *(${c.translation})*` : ''}`)
    lines.push('')
  }
  lines.push('## What the investigators found')
  lines.push('')
  lines.push(rec.probable_cause)
  lines.push('')
  const chainText = rec.chain.map(([a, b]) => `${label(a)} → ${label(b)}`)
  if (chainText.length) {
    lines.push('The causal chain, as encoded in the graph:')
    lines.push('')
    for (const c of chainText) lines.push(`- ${c}`)
    lines.push('')
  }
  for (const role of ['initiating', 'contributing', 'latent', 'outcome']) {
    const fs = rec.factors.filter((f) => f.role === role)
    if (!fs.length) continue
    lines.push(`**${role[0].toUpperCase() + role.slice(1)} factors.** ` + fs.map((f) => `*${label(f.id)}*: ${f.evidence || ''}`).join(' '))
    lines.push('')
  }
  if (rec.dissent && rec.dissent.length) {
    lines.push('## Where the agencies disagreed')
    lines.push('')
    for (const d of rec.dissent) lines.push(`- **${d.agency}** (${d.topic || 'findings'}): ${d.position}`)
    lines.push('')
  }
  if (rec.recommendations.length || (rec.safety_changes || []).length) {
    lines.push('## What changed')
    lines.push('')
    for (const r of rec.recommendations) lines.push(`- ${r.id ? `**${r.id}**${r.to ? ` to ${r.to}` : ''}: ` : ''}${r.text}${r.status && r.status !== 'unknown' ? ` *(${r.status.replace(/_/g, ' ')})*` : ''}${r.outcome ? ` — ${r.outcome}` : ''}`)
    for (const s of rec.safety_changes || []) lines.push(`- ${s}`)
    lines.push('')
  }
  if (rec.related && rec.related.length) {
    lines.push('## Related accidents')
    lines.push('')
    lines.push(rec.related.map((id) => index.byId[id]?.title || id).join(', '))
    lines.push('')
  }
  lines.push('---')
  lines.push(`*Generated by Blackbox from a structured record extracted from the ${rec.agency} final report (${rec.extraction.method}, confidence ${rec.extraction.confidence}). Verify against the report before citing.*`)
  return lines.join('\n')
}

function relText(t) {
  const a = Math.abs(t)
  const sign = t < 0 ? 'before' : 'after'
  if (a < 3600) return `${a} s ${sign} the reference instant`
  if (a < 86400) return `${(a / 3600).toFixed(1)} h ${sign} the reference instant`
  return `${(a / 86400).toFixed(0)} days ${sign} the reference instant`
}

function stateText(state) {
  if (!state) return ''
  const bits = []
  if (typeof state.alt === 'number') bits.push(`${Math.round(state.alt).toLocaleString()} ft`)
  if (typeof state.ias === 'number') bits.push(`${Math.round(state.ias)} kt`)
  if (typeof state.pitch === 'number') bits.push(`pitch ${state.pitch}°`)
  if (typeof state.vs === 'number') bits.push(`${state.vs > 0 ? '+' : ''}${Math.round(state.vs)} fpm`)
  return bits.length ? ` (${bits.join(', ')})` : ''
}

/** Very small markdown → HTML for the narrative preview. */
export function markdownToHtml(md) {
  const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  const inline = (s) =>
    esc(s)
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .replace(/\*\*([^*]+)\*\*/g, '<b>$1</b>')
      .replace(/\*([^*]+)\*/g, '<i>$1</i>')
  const out = []
  let inList = false
  for (const raw of md.split('\n')) {
    const line = raw.trimEnd()
    if (line.startsWith('- ')) {
      if (!inList) { out.push('<ul>'); inList = true }
      out.push(`<li>${inline(line.slice(2))}</li>`)
      continue
    }
    if (inList) { out.push('</ul>'); inList = false }
    if (line.startsWith('# ')) out.push(`<h1>${inline(line.slice(2))}</h1>`)
    else if (line.startsWith('## ')) out.push(`<h2>${inline(line.slice(3))}</h2>`)
    else if (line === '---') out.push('<hr/>')
    else if (line) out.push(`<p>${inline(line)}</p>`)
  }
  if (inList) out.push('</ul>')
  return out.join('\n')
}
